import Author from './author';
import Data from './data';
import Fato from './fact';
import Person from './person';

type Obra = {
  ID: number;
  Imagem?: string;
  Authors?: Author[] | undefined;
  Titulo?: string;
  Material?: string;
  Altura?: string;
  Largura?: string;
  Profundidade?: string;
  Diametro?: string;
  Peso?: string;
  ValorObra?: string;
  DataInauguracao?: string;
  DatasImportantes?: Data[];
  Promotor?: string;
  Financiamento?: string;
  Propriedade?: string;
  Cidade?: string;
  Estado?: string;
  Pais?: string;
  Zona?: string;
  Bairro?: string;
  Endereco?: string;
  Latitude?: string;
  Longitude?: string;
  SuporteEspacial?: string;
  Base?: string;
  MaterialBase?: string;
  Status?: string;
  Descricao?: string;
  Fatos?: Fato[];
  Temporalidade?: string;
  Funcao?: string;
  Natureza?: string;
  Tipologia?: string;
  Execucao?: boolean;
  Classificacao?: string;
  Categoria?: string;
  Remocao?: boolean;
  Realocacao?: boolean;
  EnderecoRealocacao?: string;
  LugarRealocacao?: string;
  ZonaRealocacao?: string;
  BairroRealocacao?: string;
  DataRealocacao?: string;
  LatitudeRealocacao?: string;
  LongitudeRealocacao?: string;
  EndereçoRealocacao?: string;
  Lugar?: string;
  Renomeacao?: boolean;
  Movimentacoes?: {
    Tipo: string;
    Data: string;
    Zona?: string;
    Bairro?: string;
    Endereco?: string;
    Latitude?: string;
    Longitude?: string;
  }[];
  Tombamentos?: {
    Esfera: string;
    Data?: string;
  }[];
  Homenageados?: Person[];
  Promocao?: string;
  Revestimento?: string;
};

export default Obra;
