version: 2.1

orbs:
  node: circleci/node@7.2.1

jobs:
  build: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install:
          node-version: '26.3.0'
      - run: sudo npm install -g npm@latest
      - node/install-packages:
          pkg-manager: npm
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          command: npm run build:web
          name: Build app
  deploy: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install:
          node-version: '26.3.0'
      - run: sudo npm install -g npm@latest
      - run: sudo npm install -g vercel@latest
      - run:
          command: DEPLOYMENT_URL=$(export VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID_PROD && export VERCEL_ORG_ID=$VERCEL_ORG_ID && vercel --prod --skip-domain --yes --token $VERCEL_TOKEN)
          name: Deploy
  promote: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install:
          node-version: '26.3.0'
      - run: sudo npm install -g npm@latest
      - run: sudo npm install -g vercel@latest
      - run:
          command: export VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID_PROD && export VERCEL_ORG_ID=$VERCEL_ORG_ID && vercel promote "$DEPLOYMENT_ID" --yes --token $VERCEL_TOKEN
          name: Deploy

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
      - hold-prod:
          requires:
            - deploy
          filters:
            branches:
              only:
                - main
          type: approval
      - promote:
          context: admins
          requires:
            - hold-prod
          filters:
            branches:
              only:
                - main