version: 2.1

orbs:
  node: circleci/node@7.0.0

jobs:
  build: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install:
          node-version: '24.4.1'
      - run: sudo npm install -g npm@latest
      - node/install-packages:
          pkg-manager: npm
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          command: npm run build:web
          name: Build app
  deploy-dev: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install:
          node-version: '24.4.1'
      - run: sudo npm install -g npm@latest
      - run: sudo npm install -g vercel
      - run: sudo npm install -g now
      - run:
          command: export NOW_PROJECT_ID=$NOW_PROJECT_ID_DEV && export NOW_ORG_ID=$NOW_ORG_ID && now --prod --token $NOW_TOKEN
          name: Deploy
  deploy-qa: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install:
          node-version: '24.4.1'
      - run: sudo npm install -g npm@latest
      - run: sudo npm install -g vercel
      - run: sudo npm install -g now
      - run:
          command: export NOW_PROJECT_ID=$NOW_PROJECT_ID_QA && export NOW_ORG_ID=$NOW_ORG_ID && now --prod --token $NOW_TOKEN
          name: Deploy
  deploy-prod: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install:
          node-version: '24.4.1'
      - run: sudo npm install -g npm@latest
      - run: sudo npm install -g vercel
      - run: sudo npm install -g now
      - run:
          command: export NOW_PROJECT_ID=$NOW_PROJECT_ID_PROD && export NOW_ORG_ID=$NOW_ORG_ID && now --prod --token $NOW_TOKEN
          name: Deploy

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - hold-qa:
          requires:
            - deploy-dev
          filters:
            branches:
              only:
                - main
          type: approval
      - deploy-qa:
          requires:
            - hold-qa
          filters:
            branches:
              only:
                - main
      - hold-prod:
          requires:
            - deploy-qa
          filters:
            branches:
              only:
                - main
          type: approval
      - deploy-prod:
          context: admins
          requires:
            - hold-prod
          filters:
            branches:
              only:
                - main